// <auto-generated />
using System;
using ImportExport.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImportExport.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241111144254_InsertionDEmployees")]
    partial class InsertionDEmployees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImportExport.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeId");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            EmployeId = 1,
                            Age = 39,
                            DateOfBirth = new DateTime(1985, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Marketing",
                            FullName = "Alice Dupont",
                            PhoneNumber = "0997916876"
                        },
                        new
                        {
                            EmployeId = 2,
                            Age = 34,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "IT",
                            FullName = "Bernard Lefevre",
                            PhoneNumber = "0997916877"
                        },
                        new
                        {
                            EmployeId = 3,
                            Age = 36,
                            DateOfBirth = new DateTime(1988, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "HR",
                            FullName = "Caroline Martin",
                            PhoneNumber = "0997916878"
                        },
                        new
                        {
                            EmployeId = 4,
                            Age = 32,
                            DateOfBirth = new DateTime(1992, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Sales",
                            FullName = "David Dubois",
                            PhoneNumber = "0997916879"
                        },
                        new
                        {
                            EmployeId = 5,
                            Age = 33,
                            DateOfBirth = new DateTime(1990, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Marketing",
                            FullName = "Daniel Kadima",
                            PhoneNumber = "0997916880"
                        },
                        new
                        {
                            EmployeId = 6,
                            Age = 38,
                            DateOfBirth = new DateTime(1986, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "IT",
                            FullName = "Elisabeth Garnier",
                            PhoneNumber = "0997916881"
                        },
                        new
                        {
                            EmployeId = 7,
                            Age = 40,
                            DateOfBirth = new DateTime(1984, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Finance",
                            FullName = "François Lemoine",
                            PhoneNumber = "0997916882"
                        },
                        new
                        {
                            EmployeId = 8,
                            Age = 33,
                            DateOfBirth = new DateTime(1991, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "HR",
                            FullName = "Gabrielle Dumont",
                            PhoneNumber = "0997916883"
                        },
                        new
                        {
                            EmployeId = 9,
                            Age = 41,
                            DateOfBirth = new DateTime(1983, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "IT",
                            FullName = "Henri Clément",
                            PhoneNumber = "0997916884"
                        },
                        new
                        {
                            EmployeId = 10,
                            Age = 29,
                            DateOfBirth = new DateTime(1995, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Sales",
                            FullName = "Isabelle Lefranc",
                            PhoneNumber = "0997916885"
                        },
                        new
                        {
                            EmployeId = 11,
                            Age = 37,
                            DateOfBirth = new DateTime(1987, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Marketing",
                            FullName = "Julien Moreau",
                            PhoneNumber = "0997916886"
                        },
                        new
                        {
                            EmployeId = 12,
                            Age = 30,
                            DateOfBirth = new DateTime(1994, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "IT",
                            FullName = "Katherine Bernard",
                            PhoneNumber = "0997916887"
                        },
                        new
                        {
                            EmployeId = 13,
                            Age = 43,
                            DateOfBirth = new DateTime(1981, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Finance",
                            FullName = "Louis Lefevre",
                            PhoneNumber = "0997916888"
                        },
                        new
                        {
                            EmployeId = 14,
                            Age = 31,
                            DateOfBirth = new DateTime(1993, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "HR",
                            FullName = "Marie Lefevre",
                            PhoneNumber = "0997916889"
                        },
                        new
                        {
                            EmployeId = 15,
                            Age = 34,
                            DateOfBirth = new DateTime(1990, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Sales",
                            FullName = "Nicolas Dufresne",
                            PhoneNumber = "0997916890"
                        },
                        new
                        {
                            EmployeId = 16,
                            Age = 32,
                            DateOfBirth = new DateTime(1992, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Marketing",
                            FullName = "Olivier Vidal",
                            PhoneNumber = "0997916891"
                        },
                        new
                        {
                            EmployeId = 17,
                            Age = 35,
                            DateOfBirth = new DateTime(1989, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "IT",
                            FullName = "Pauline Chretien",
                            PhoneNumber = "0997916892"
                        },
                        new
                        {
                            EmployeId = 18,
                            Age = 38,
                            DateOfBirth = new DateTime(1986, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Finance",
                            FullName = "Quentin Renaud",
                            PhoneNumber = "0997916893"
                        },
                        new
                        {
                            EmployeId = 19,
                            Age = 33,
                            DateOfBirth = new DateTime(1991, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "HR",
                            FullName = "Raphaël Dufresne",
                            PhoneNumber = "0997916894"
                        },
                        new
                        {
                            EmployeId = 20,
                            Age = 34,
                            DateOfBirth = new DateTime(1990, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Sales",
                            FullName = "Sophie Berger",
                            PhoneNumber = "0997916895"
                        },
                        new
                        {
                            EmployeId = 21,
                            Age = 39,
                            DateOfBirth = new DateTime(1985, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Marketing",
                            FullName = "Thomas Lefranc",
                            PhoneNumber = "0997916896"
                        },
                        new
                        {
                            EmployeId = 22,
                            Age = 36,
                            DateOfBirth = new DateTime(1988, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "IT",
                            FullName = "Ursula David",
                            PhoneNumber = "0997916897"
                        },
                        new
                        {
                            EmployeId = 23,
                            Age = 30,
                            DateOfBirth = new DateTime(1994, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Finance",
                            FullName = "Vincent Boucher",
                            PhoneNumber = "0997916898"
                        },
                        new
                        {
                            EmployeId = 24,
                            Age = 32,
                            DateOfBirth = new DateTime(1992, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "HR",
                            FullName = "Wendy Dumont",
                            PhoneNumber = "0997916899"
                        },
                        new
                        {
                            EmployeId = 25,
                            Age = 37,
                            DateOfBirth = new DateTime(1987, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Sales",
                            FullName = "Xavier Girard",
                            PhoneNumber = "0997916900"
                        },
                        new
                        {
                            EmployeId = 26,
                            Age = 35,
                            DateOfBirth = new DateTime(1989, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Marketing",
                            FullName = "Yannick Bernard",
                            PhoneNumber = "0997916901"
                        },
                        new
                        {
                            EmployeId = 27,
                            Age = 33,
                            DateOfBirth = new DateTime(1991, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "IT",
                            FullName = "Zoe Lefevre",
                            PhoneNumber = "0997916902"
                        },
                        new
                        {
                            EmployeId = 28,
                            Age = 43,
                            DateOfBirth = new DateTime(1980, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "IT",
                            FullName = "Noel Kazadi",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            EmployeId = 29,
                            Age = 38,
                            DateOfBirth = new DateTime(1985, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "HR",
                            FullName = "Joel Kirengo",
                            PhoneNumber = "234-567-8901"
                        },
                        new
                        {
                            EmployeId = 30,
                            Age = 31,
                            DateOfBirth = new DateTime(1992, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Finance",
                            FullName = "Joel Muhindo",
                            PhoneNumber = "345-678-9012"
                        },
                        new
                        {
                            EmployeId = 31,
                            Age = 35,
                            DateOfBirth = new DateTime(1988, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Sales",
                            FullName = "Claudien Green",
                            PhoneNumber = "456-789-0123"
                        },
                        new
                        {
                            EmployeId = 32,
                            Age = 33,
                            DateOfBirth = new DateTime(1990, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Marketing",
                            FullName = "Jonathan Mutendi",
                            PhoneNumber = "567-890-1234"
                        },
                        new
                        {
                            EmployeId = 33,
                            Age = 43,
                            DateOfBirth = new DateTime(1980, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "IT",
                            FullName = "Gabriel Kanyibu",
                            PhoneNumber = "0997916872"
                        },
                        new
                        {
                            EmployeId = 34,
                            Age = 38,
                            DateOfBirth = new DateTime(1985, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "HR",
                            FullName = "Bob Smith",
                            PhoneNumber = "0997916873"
                        },
                        new
                        {
                            EmployeId = 35,
                            Age = 38,
                            DateOfBirth = new DateTime(1985, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "HR",
                            FullName = "Bob Smith",
                            PhoneNumber = "0997916873"
                        },
                        new
                        {
                            EmployeId = 36,
                            Age = 38,
                            DateOfBirth = new DateTime(1985, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "HR",
                            FullName = "Bob Smith",
                            PhoneNumber = "0997916873"
                        },
                        new
                        {
                            EmployeId = 37,
                            Age = 31,
                            DateOfBirth = new DateTime(1992, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Finance",
                            FullName = "Charlie Brown",
                            PhoneNumber = "0997916874"
                        },
                        new
                        {
                            EmployeId = 38,
                            Age = 35,
                            DateOfBirth = new DateTime(1988, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Sales",
                            FullName = "Diana Green",
                            PhoneNumber = "0997916875"
                        },
                        new
                        {
                            EmployeId = 39,
                            Age = 33,
                            DateOfBirth = new DateTime(1990, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Departement = "Marketing",
                            FullName = "Edward White",
                            PhoneNumber = "0997916876"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
